public class Multiplica {
    public static Decimal mult(Decimal a1){
    Decimal convertKmToMiles=a1*0.621371;
        Return convertKmToMiles;
    }
    
    public static Decimal multi(Decimal a2){
    Decimal convertMilesToKm=a2*1.60934;
        Return convertMilesToKm;
    }
    
    public static Integer mult(Integer a3){
    Integer cubeVolume=a3*a3*a3;
        Return cubeVolume;
    }
    
}