public class TestList {
    	public List<Integer> add(Integer a1, Integer a2, Integer a3, Integer a4, Integer a5, 
                               Integer a6, Integer a7, Integer a8, Integer a9, Integer a10){
    	List<Integer> numList=new List<Integer>();
        numList.add(a1);
    	numList.add(a2);
    	numList.add(a3);
    	numList.add(a4);
    	numList.add(a5);
    	numList.add(a6);
    	numList.add(a7);
    	numList.add(a8);
    	numList.add(a9);
   	 	numList.add(a10);
        Return numList;                           
    }
}